# creates binary for Debian distro

name: Debian Release

on: 
 workflow_dispatch:
 release:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create binary
        run: |
            sudo apt install dpkg-dev tree
            tree
            ls -lath
            echo $PWD
            pwd
            dpkg-deb --root-owner-group --build ../snorem-diagnostics/ .
            ls -lath .
        
      - name: Move package to repository 
        run: |
          git config --global credential.helper store
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit package to repository
        run: |
          git add .
          git commit -m "Adding binary to repo"
          git push origin main

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
